### ISSUE TITLE
Uptime

### ISSUE THREAD

**Issue by SamArroyos22** [Naught0/qtbot#1]
How would i get Uptime to work?

i Keep getting this

`Ignoring exception in command uptime
Traceback (most recent call last):
  File "C:\Users\Samar\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\ext\commands\bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "C:\Users\Samar\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\ext\commands\core.py", line 367, in invoke
    yield from self.prepare(ctx)
  File "C:\Users\Samar\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\ext\commands\core.py", line 345, in prepare
    yield from self._parse_arguments(ctx)
  File "C:\Users\Samar\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\ext\commands\core.py", line 304, in _parse_arguments
    transformed = yield from self.transform(ctx, param)
  File "C:\Users\Samar\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\ext\commands\core.py", line 212, in transform
    raise MissingRequiredArgument('{0.name} is a required argument that is missing.'.format(param))
discord.ext.commands.errors.MissingRequiredArgument: ctx is a required argument that is missing.`

**Comment by Naught0** [comment]
What version of Python are you using? Also what version of the Discord.py library are you using? All the command does it check the current time and then subtract that from the original time when the bot was executed.

**Comment by Naught0** [comment]
I have qtbot running most of the time on my personal server, so I can figure out a way that you can invite him to your channel if you want.

**Comment by Naught0** [comment]
Scratch that. Try to pull the repo again. I was just migrating to the new version of the discord library. I may have fixed a few things after you pulled the code...

**Comment by SamArroyos22** [comment]
ok @Naught0

**Comment by SamArroyos22** [comment]
i still get this error, Im new to datetime, so thats why i know nothing about how to make an uptime



`Ignoring exception in command uptime
Traceback (most recent call last):
  File "C:\Users\Samar\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\ext\commands\bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "C:\Users\Samar\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\ext\commands\core.py", line 367, in invoke
    yield from self.prepare(ctx)
  File "C:\Users\Samar\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\ext\commands\core.py", line 345, in prepare
    yield from self._parse_arguments(ctx)
  File "C:\Users\Samar\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\ext\commands\core.py", line 304, in _parse_arguments
    transformed = yield from self.transform(ctx, param)
  File "C:\Users\Samar\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\ext\commands\core.py", line 212, in transform
    raise MissingRequiredArgument('{0.name} is a required argument that is missing.'.format(param))
discord.ext.commands.errors.MissingRequiredArgument: ctx is a required argument that is missing.`

**Comment by Naught0** [comment]
If you have the rewrite library, then this shouldn't happen. It sounds like you're missing the `ctx` parameter somewhere. What version of the library do you see when you run `pip show discord.py`?

**Comment by SamArroyos22** [comment]
@Naught0 http://prntscr.com/g7ayfm

**Comment by Naught0** [comment]
There we go. You're using the `async` version of discord.py. I'm on the version labelled `rewrite`. To run the bot, you'll need to `pip uninstall discord.py` and `python3 -m pip install -U git+https://github.com/Rapptz/discord.py@rewrite`. I think that should solve some issues. I'm working on making my commands more secure so in the future so the bot can become public.
